"""Turn the pipeline's own numbers into a report a reader can check.

Phase V of TASK.md. The rule this file exists to enforce: publish the
failures. A validation step that only reports pass rates when they are good
is not a validation step.

Run:  python3 -m pipeline.audit
"""

from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
PROCESSED = HERE / "data" / "processed"
AUDIT = HERE / "audit"


def read_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def main() -> None:
    report_path = AUDIT / "normalize-report.json"
    if not report_path.exists():
        raise SystemExit("run `python3 -m pipeline.normalize` first")
    report = json.loads(report_path.read_text())

    panel = read_csv(PROCESSED / "school-enrollment-by-grade.csv")
    school_year = read_csv(PROCESSED / "school-year.csv")
    registry = read_csv(PROCESSED / "schools.csv")
    district_year = read_csv(PROCESSED / "district-year.csv")
    district_grade = read_csv(PROCESSED / "district-enrollment-by-grade.csv")
    recon = read_csv(PROCESSED / "source-reconciliation.csv")

    lines: list[str] = []
    add = lines.append

    add("# Validation report")
    add("")
    add("Generated by `pipeline/audit.py` from the pipeline's own output. Every")
    add("number here is a check the archive ran on itself, failures included.")
    add("")

    # ---- coverage -------------------------------------------------------
    add("## Coverage")
    add("")
    counts = report.get("counts", {})
    add("| Table | Rows |")
    add("|---|---:|")
    for label, path in (
        ("`school-enrollment-by-grade.csv`", PROCESSED / "school-enrollment-by-grade.csv"),
        ("`school-year.csv`", PROCESSED / "school-year.csv"),
        ("`schools.csv`", PROCESSED / "schools.csv"),
        ("`district-enrollment-by-grade.csv`", PROCESSED / "district-enrollment-by-grade.csv"),
        ("`district-year.csv`", PROCESSED / "district-year.csv"),
        ("`source-reconciliation.csv`", PROCESSED / "source-reconciliation.csv"),
    ):
        rows = read_csv(path)
        add(f"| {label} | {len(rows):,} |")
    add("")

    school_years = sorted({int(r["year"]) for r in panel}) if panel else []
    district_years = sorted({int(r["year"]) for r in district_grade}) if district_grade else []
    trend_years = sorted({int(r["year"]) for r in district_year}) if district_year else []
    if school_years:
        add(f"- School panel: **{school_years[0]}–{school_years[-1]}**, "
            f"{len(school_years)} years.")
    if district_years:
        add(f"- District panel: **{district_years[0]}–{district_years[-1]}**, "
            f"{len(district_years)} years.")
    if trend_years:
        add(f"- District trends: **{trend_years[0]}–{trend_years[-1]}** "
            f"(the only series reaching before 1986).")
    add("")

    # ---- schools per year ----------------------------------------------
    add("## Schools per year")
    add("")
    add("A year whose school count departs sharply from its neighbours is a")
    add("parse fault until shown otherwise.")
    add("")
    per_year: dict[int, set] = defaultdict(set)
    for row in school_year:
        per_year[int(row["year"])].add(row["school_code"])
    add("| Year | Schools | With CDE enrollment | With CDE teacher FTE | With coordinates |")
    add("|---|---:|---:|---:|---:|")
    for year in sorted(per_year):
        rows = [r for r in school_year if int(r["year"]) == year]
        add(f"| {year} | {len(per_year[year]):,} | "
            f"{sum(1 for r in rows if r['enrollment_total_cde']):,} | "
            f"{sum(1 for r in rows if r['teacher_fte_cde']):,} | "
            f"{sum(1 for r in rows if r['latitude']):,} |")
    add("")

    # ---- reconciliation -------------------------------------------------
    add("## CDE against NCES CCD")
    add("")
    add("Pre-kindergarten is excluded from the gap column because CCD")
    add("publishes none for Colorado in any year. Including it would show a")
    add("gap of roughly 31,000 pupils that is entirely definitional.")
    add("")
    if recon:
        add("| Year | Matched schools | Exact agreement | Median diff | Gap excluding PK |")
        add("|---|---:|---:|---:|---:|")
        for row in recon:
            matched = int(row["matched"] or 0)
            exact = int(row["exact_agreement"] or 0)
            share = f"{exact / matched:.1%}" if matched else "-"
            add(f"| {row['year']} | {matched:,} | {exact:,} ({share}) | "
                f"{row['median_abs_diff']} | {int(row['gap_excluding_prek'] or 0):+,} |")
    else:
        add("_No overlapping years._")
    add("")

    # ---- row totals -----------------------------------------------------
    add("## Row-total checksums")
    add("")
    add("Every source table prints its own row total. Summing the grade cells")
    add("and comparing is the one mechanical proof a row was read correctly.")
    add("")
    meta = report.get("parse_meta", {})
    add("| Source | Year | Rows checked | Pass | Fail |")
    add("|---|---|---:|---:|---:|")
    for year, info in sorted((meta.get("cde_school") or {}).items()):
        if "row_total_pass" not in info:
            continue
        passed, failed = info["row_total_pass"], info["row_total_fail"]
        add(f"| CDE spreadsheet | {year} | {passed + failed:,} | {passed:,} | {failed:,} |")
    for year, info in sorted((meta.get("yearbooks") or {}).items()):
        grade_info = (info or {}).get("district_by_grade", {})
        if "row_total_pass" not in grade_info:
            continue
        passed, failed = grade_info["row_total_pass"], grade_info["row_total_fail"]
        add(f"| Yearbook (re-OCR) | {year} | {passed + failed:,} | {passed:,} | {failed:,} |")
    add("")

    # ---- joins ----------------------------------------------------------
    add("## Joins")
    add("")
    for label, key in (("CDE rows matched to an NCES school id", "cde_rows_matched_to_nces_id"),
                       ("Yearbook rows matched to a district code", "yearbook_rows_matched_to_district_code")):
        info = report.get(key)
        if not info:
            continue
        rate = info.get("rate")
        add(f"- {label}: **{info['matched']:,} of {info['total']:,}**"
            + (f" ({rate:.1%})" if rate is not None else ""))
    add("")
    add("An unmatched row is kept, not dropped. A school with no NCES id still")
    add("carries its CDE code and its counts; it simply cannot be followed")
    add("across a rename.")
    add("")

    # ---- closures -------------------------------------------------------
    add("## Closure labels")
    add("")
    add("Auto-labelled from the data alone and never hand-verified, by")
    add("decision (`decision-log.md`, D6). The confidence column is the")
    add("honest part of this table.")
    add("")
    by_label: dict[tuple, int] = defaultdict(int)
    for row in registry:
        by_label[(row["closure_label"], row["closure_confidence"])] += 1
    add("| Label | Confidence | Schools |")
    add("|---|---|---:|")
    for (label, confidence), count in sorted(by_label.items(), key=lambda kv: -kv[1]):
        add(f"| {label} | {confidence} | {count:,} |")
    add("")

    # ---- known gaps -----------------------------------------------------
    add("## Known gaps")
    add("")
    add("- Pre-kindergarten exists on the CDE side only.")
    add("- School-level teacher FTE covers twenty-two CDE years, 2000-2024.")
    add("  2017 is absent because CDE's file for it duplicates 2016 byte for")
    add("  byte, and no ratio report was published for 2020 or 2021. CCD")
    add("  carries school FTE from 1986 and district FTE from 1987.")
    add("- The 1986–1999 tier is district grain: those yearbooks contain no")
    add("  school-level table at all.")
    add("- CCD ends before the last CDE year, so the most recent years have no")
    add("  second source and no reconciliation row.")
    add("- Coordinates are carried backward from a recent directory, so a")
    add("  school that moved buildings carries its later location.")
    add("")

    out = AUDIT / "validation.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out}")
    print("\n".join(lines[:40]))


if __name__ == "__main__":
    main()
